### ISSUE TITLE
Backpacked (1.3.0) for MC1.12 - Have baubles1.5.2 - error NoClassDefFound

### ISSUE THREAD

**Issue by Caimbul** [MrCrayfish/Backpacked#30]
Hiya Mr. Crayfish.

Trying to get your mods working in 1.12 (due to other mods) I have Baubles 1.5.2 loaded.
Getting following error. 

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/mrcrayfish/backpacked/item/BaubleBackpackItem
Exit Code: 255

Should I use a different version of Baubles? I'll put the log below.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar)
  Backpacked (backpacked-1.3.0-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 11/23/20 1:50 PM
Description: Initializing game

java.lang.NoClassDefFoundError: com/mrcrayfish/backpacked/item/BaubleBackpackItem
	at com.mrcrayfish.backpacked.core.ModItems.registerBackpack(ModItems.java:33)
	at com.mrcrayfish.backpacked.core.ModItems.init(ModItems.java:25)
	at com.mrcrayfish.backpacked.Backpacked.onModConstruct(Backpacked.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.mrcrayfish.backpacked.item.BaubleBackpackItem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: baubles/api/IBauble
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: baubles.api.IBauble
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.backpacked.core.ModItems.registerBackpack(ModItems.java:33)
	at com.mrcrayfish.backpacked.core.ModItems.init(ModItems.java:25)
	at com.mrcrayfish.backpacked.Backpacked.onModConstruct(Backpacked.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1628168080 bytes (1552 MB) / 1946157056 bytes (1856 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                                    | Signature                                |
	|:----- |:----------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| LC    | minecraft         | 1.12.2       | minecraft.jar                             | None                                     |
	| LC    | mcp               | 9.42         | minecraft.jar                             | None                                     |
	| LC    | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge             | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy | 1.0.0        | minecraft.jar                             | None                                     |
	| LC    | littletilescore   | 1.0.0        | minecraft.jar                             | None                                     |
	| L     | backpacked        | 1.3.0        | backpacked-1.3.0-1.12.2.jar               | None                                     |
	| L     | baubles           | 1.5.2        | Baubles-1.12-1.5.2.jar                    | None                                     |
	| L     | chiseled_me       | 2.0.0.1      | chiseled-me-1.12.2-2.0.0.1.jar            | None                                     |
	| L     | chiselsandbits    | 14.33        | chiselsandbits-14.33.jar                  | None                                     |
	| L     | creativecore      | 1.10.0       | CreativeCore_v1.10.34_mc1.12.2.jar        | None                                     |
	| L     | littletiles       | 1.5.0        | LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar | None                                     |

	Loaded coremods (and transformers): 
Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1.jar)
  dev.necauqua.mods.cm.asm.Plugin
CreativePatchingLoader (CreativeCore_v1.10.34_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
Backpacked (backpacked-1.3.0-1.12.2.jar)
  com.mrcrayfish.backpacked.asm.BackpackedTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.0.52 310.90.10.05b46' Renderer: 'NVIDIA GeForce 9400M OpenGL Engine'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce 9400M OpenGL Engine GL version 2.1 NVIDIA-10.0.52 310.90.10.05b46, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU P7550 @ 2.26GHz

**Comment by MrCrayfish** [comment]
Going to say that Backpacked loaded before Baubles. I think I may have forgot to define Baubles as a dependency.

**Comment by MrCrayfish** [comment]
Can you try this version? I'm unable to reproduce the issue so I am hoping you can test it. Make sure to extract the zip as the jar file is inside.
[backpacked-1.4.3-1.12.2.zip](https://github.com/MrCrayfish/Backpacked/files/6204471/backpacked-1.4.3-1.12.2.zip)

**Comment by Caimbul** [comment]
Hiya!

I've added the jar to the mod folder, and Forge loaded. Loaded up her game
world as well. So, it looks like this new jar is the ticket! (She has to go
make some backpacks now..)

Thanks for your help. You made a 10yr olds day. (Also, I got some points
because when I told her you emailed me, she was like 'What!?! He's famous!'
lol..) Thanks for continuing to support your older mods.

Stay safe!
